FROM php:8.2-apache

# Configura Apache para escuchar en el puerto 10000 (el que Render requiere)
RUN sed -i 's/80/10000/' /etc/apache2/ports.conf \
 && sed -i 's/80/10000/' /etc/apache2/sites-available/000-default.conf

# Copia tu código fuente
COPY . /var/www/html/

# Instala extensiones PHP necesarias
RUN docker-php-ext-install mysqli

# Expón el puerto que Render usará
EXPOSE 10000

# Comando para iniciar Apache
CMD ["apache2-foreground"]
